name: Build and publish container images
on:
  push:
    branches:
      - master
    paths:
      - containerfiles/*

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to docker hub
        run: podman login docker.io -u "$username" -p "$password"
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build database
        run: podman build -f containerfiles/database -t cda-postgres

      - name: Upload database to docker hub
        run: podman push cda-postgres docker.io/akarien/cda:postgres


      - name: Build frontend builder
        run: podman build -f containerfiles/web-console-builder -t cda-web-builder

      - name: Upload frontend builder to docker hub
        run: podman push cda-web-builder docker.io/akarien/cda:web-builder