name: CI
on:
  push:
    branches:
      - master

jobs:
  container_images:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install podman


      - name: Build database
        run: podman build -f containerfiles/database -t cda-postgres

      - name: Database artifact
        uses: actions/upload-artifact@v6
        with:
          name: db-image
          path: ~/.local/share/containers/${podman images \
                                              --format='{{.Names}} {{.Id}}' | \
                                              grep cda-postgres | \
                                              awk '{ print $2 }'}
                                          }


      - name: Build frontend builder
        run: podman build -f containerfiles/web-console-builder -t cda-web-builder

      - name: Frontend builder artifact
        uses: actions/upload-artifact@v6
        with:
          name: db-image
          path: ~/.local/share/containers/${podman images \
                                              --format='{{.Names}} {{.Id}}' | \
                                              grep cda-web-builder | \
                                              awk '{ print $2 }' \
                                          }