name: CI
on:
  push:
    branches:
      - master

jobs:
  container_images:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to docker hub
        run: podman login -u "$username" -p "$password"
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      - name: Build database
        run: podman build -f containerfiles/database -t cda-postgres

      - name: Upload database to docker hub
        run: podman push cda-postgres https://hub.docker.com/akarien/cda:postgres


      - name: Build frontend builder
        run: podman build -f containerfiles/web-console-builder -t cda-web-builder

      - name: Upload frontend builder to docker hub
        run: podman push cda-web-builder https://hub.docker.com/akarien/cda:web-builder